apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-2
  name: web-2-service
spec:
  ports:
  - name: web-2-nginx-port
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: web-2
  type: ClusterIP


