apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-1-deployment
  labels:
    app: web-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-1
  template:
    metadata:
      labels:
        app: web-1
    spec:
      initContainers:
        - name: init-web-1
          image: ubuntu:latest
          command: ["/bin/sh", "-c"]
          args:
          - apt-get update && apt-get install -y unzip curl && curl -o source-code.zip https://www.free-css.com/assets/files/free-css-templates/download/page296/little-fashion.zip && unzip source-code.zip -d /var/www/quoctran.com/public/web_1 && mv /var/www/quoctran.com/public/web_1/2127_little_fashion/* /var/www/quoctran.com/public/web_1
          volumeMounts:
            - name: nginx-source-volume-1
              mountPath: /var/www/quoctran.com/public/web_1
      containers:
        - name: web-1
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-source-volume-1
              mountPath: /var/www/quoctran.com/public/web_1
            - name: nginx-config-volume-1
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-source-volume-1
          emptyDir: {}
        - name: nginx-config-volume-1
          configMap:
            name: nginx-config-file-1

