apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-1
  name: web-1-service
spec:
  ports:
  - name: web-1-nginx-port
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: web-1
  type: ClusterIP


