apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-proxy
  name: nginx-proxy-service
spec:
  ports:
  - name: nginx-proxy-port
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30000
  selector:
    app: nginx-proxy
  type: NodePort


